version: '3.9'

services:
  server:
    build:
      context: .
    ports:
      - "8501:8501"
    volumes:
      - ./:/app                # Mount the whole project folder
    env_file:
      - .env                    # <-- Add this line
    command: >
      streamlit run src/streamlit_app.py
      --server.port=8501
      --server.address=0.0.0.0